import type { LucideIcon } from "lucide-react"
import {
  Download,
  Upload,
  ShieldOff,
  Hash,
  Footprints,
  Zap,
  Globe,
  Clock,
  Headphones,
  CircleSlash,
  Cookie,
  Gauge,
  Equal,
  Shield,
  ShieldCheck,
  Cloud,
  Bot,
  Server,
  Code2,
  CloudRain,
  Repeat,
  Bomb,
  Swords,
  Network,
  Radio,
  Activity,
  Plug,
  Wifi,
  Link,
  Gamepad2,
  Car,
  Key,
  Database,
  Box,
  Smartphone,
  Type,
  Folder,
  Monitor,
  MonitorPlay,
  MapPin,
  CheckCircle,
  BarChart3,
  Layers,
  Cpu,
} from "lucide-react"

export const METHOD_ICONS: Record<string, LucideIcon> = {
  GET: Download,
  POST: Upload,
  OVH: ShieldOff,
  RHEX: Hash,
  STOMP: Footprints,
  STRESS: Zap,
  DYN: Globe,
  DOWNLOADER: Download,
  SLOW: Clock,
  HEAD: Headphones,
  NULL: CircleSlash,
  COOKIE: Cookie,
  PPS: Gauge,
  EVEN: Equal,
  GSB: Shield,
  DGB: ShieldCheck,
  AVB: Cloud,
  BOT: Bot,
  APACHE: Server,
  XMLRPC: Code2,
  CFB: Cloud,
  CFBUAM: CloudRain,
  BYPASS: Repeat,
  BOMB: Bomb,
  KILLER: Swords,
  TOR: Shield,
  TCP: Network,
  UDP: Radio,
  SYN: Activity,
  "OVH-UDP": ShieldOff,
  CPS: Plug,
  ICMP: Wifi,
  CONNECTION: Link,
  VSE: Gamepad2,
  TS3: Headphones,
  FIVEM: Car,
  "FIVEM-TOKEN": Key,
  MEM: Database,
  NTP: Clock,
  MCBOT: Bot,
  MINECRAFT: Box,
  MCPE: Smartphone,
  DNS: Globe,
  CHAR: Type,
  CLDAP: Folder,
  ARD: Monitor,
  RDP: MonitorPlay,
}

export const TOOL_ICONS: Record<string, LucideIcon> = {
  CFIP: MapPin,
  DNS: Globe,
  TSSRV: Radio,
  PING: Wifi,
  CHECK: CheckCircle,
  CHECKHOST: Server,
  DSTAT: BarChart3,
}

export const METHOD_TYPE_ICONS: Record<string, LucideIcon> = {
  layer7: Layers,
  layer4: Cpu,
}
